import "./globals.css";

import { Inter } from "next/font/google";
import type { Metadata } from "next";
import { bootstrap } from "global-agent";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  bootstrap();

  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
